
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.*;
import static org.junit.Assert.*;
import java.time.LocalDateTime;

public class TaskTest {

    @After
    public void tearDown() {
        Task.clear();
    }

    @Test
    public void Task_instantiatesCorrectly_true() {
        Task myTask = new Task("Mow the lawn");
        assertEquals(true, myTask instanceof Task);
    }

    @Test
    public void Task_instantiatesWithDescription_String() {
        Task myTask = new Task("Mow the lawn");
        assertEquals("Mow the lawn", myTask.getDescription());
    }

    @Test
    public void isCompleted_isFalseAfterInstantiation_false() {
        Task myTask = new Task("Mow the lawn");
        assertEquals(false, myTask.isCompleted());
    }

    @Test
    public void getCreatedAt_instantiatesWithCurrentTime_today() {
        Task myTask = new Task("Mow te lawn");
        assertEquals(LocalDateTime.now().getDayOfWeek(), myTask.getCreatedAt().getDayOfWeek());
    }

    @Test
    public void all_returnsAllInstancesOfTask_true() {
        Task firtTask = new Task("Mow the lawn");
        Task secondTask = new Task("Buy groceries");
        assertEquals(true, Task.all().contains(secondTask));
    }

    @Test 
    public void clear_empptiesAllTasksFromArrayList_0() {
        Task myTask = new Task("ow the lawn");
        Task.clear();
        assertEquals(Task.all().size(), 0);
    }

    @Test
    public void getId_tasksInstantantiateWithAnID_1() {
        Task.clear();  // Remember, the test will fail without this line! We need to empty leftover Tasks from previous tests!
        Task myTask = new Task("Mow te lawn");
        assertEquals(1, myTask.getId());
    }

    @Test
    public void find_returnsTaskWitSameId_secondTask() {
        Task firstTask = new Task("Mow the lawn");
        Task secondTask = new Task("Buy groceries");
        assertEquals(Task.find(secondTask.getId()), secondTask);
    }
}
